# Generated by Django 5.2.9 on 2026-03-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_is_broadcast_message_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('audio', 'Audio'), ('poll', 'Poll'), ('capsule', 'Time Capsule')], default='text', max_length=10),
        ),
    ]
