# Generated by Django 5.2.9 on 2026-03-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('audio', 'Audio'), ('poll', 'Poll'), ('capsule', 'Time Capsule'), ('location', 'Location')], default='text', max_length=10),
        ),
    ]
