# Generated by Django 5.2.9 on 2026-03-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_blockeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_view_once',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
