# Generated by Django 5.2.9 on 2026-03-13 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_scheduledcall'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledcall',
            name='message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_call', to='chat.message'),
        ),
    ]
