# Generated by Django 5.2.9 on 2026-03-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_scheduledcall_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='related_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
