# Generated by Django 5.2.9 on 2026-03-14 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_calllog_story_storyviewer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='text_style',
            field=models.CharField(choices=[('gradient1', 'Ocean Blue'), ('gradient2', 'Sunset'), ('gradient3', 'Neon Purple'), ('gradient4', 'Emerald'), ('gradient5', 'Midnight'), ('plain', 'Plain Dark')], default='gradient1', max_length=20),
        ),
        migrations.AddField(
            model_name='story',
            name='visible_to',
            field=models.ManyToManyField(blank=True, related_name='visible_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='story',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('selected', 'Selected Users')], default='public', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='storyviewer',
            unique_together={('story', 'user')},
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(default='Instant Room', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('require_admission', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admitted', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='chat.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('room', 'user')},
            },
        ),
    ]
