# Generated by Django 5.2.9 on 2026-03-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_background',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
