# Generated by Django 5.2.9 on 2026-03-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_chat_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privacy_last_seen',
            field=models.CharField(default='everyone', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_profile_photo',
            field=models.CharField(default='everyone', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
