# Generated by Django 5.2.9 on 2026-03-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_seen_tour',
            field=models.BooleanField(default=False),
        ),
    ]
